[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[test-phone]
type=endpoint
context=ivr-inbound
disallow=all
allow=ulaw,alaw
auth=test-phone-auth
aors=test-phone-aor

[test-phone-auth]
type=auth
auth_type=userpass
password=test
username=test-phone

[test-phone-aor]
type=aor
max_contacts=1
